[{"id":0,"href":"/en/posts/bug_psutil/","title":"BUG | AttributeError: module 'psutil' has no attribute 'Process'","section":"Blog","content":"When starting a Jupyter notebook and switching to a specific environment, you may encounter an error message stating AttributeError: module 'psutil' has no attribute 'Process'.\nTo resolve this issue, you can try installing a specific version of the psutil library, namely version 5.9.4, using the following command:\npip install psutil==5.9.4 "},{"id":1,"href":"/en/docs/about/","title":"About","section":"Docs","content":"Read More,\nThink More,\nWrite More.\n"}]